/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones = 'Asia/Ho_Chi_Minh';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    news: News;
    'news-categories': NewsCategory;
    media: Media;
    videos: Video;
    'contact-requests': ContactRequest;
    users: User;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media' | 'videos';
    };
  };
  collectionsSelect: {
    news: NewsSelect<false> | NewsSelect<true>;
    'news-categories': NewsCategoriesSelect<false> | NewsCategoriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    videos: VideosSelect<false> | VideosSelect<true>;
    'contact-requests': ContactRequestsSelect<false> | ContactRequestsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('vi' | 'en') | ('vi' | 'en')[];
  globals: {};
  globalsSelect: {};
  locale: 'vi' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Write, review, schedule and publish news. Articles appear on the site only once published.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  /**
   * Aim for 40–90 characters with the main keyword. The SEO title is tuned in the SEO tab.
   */
  title: string;
  searchText?: string | null;
  /**
   * Required to publish. Also the default SEO description (Google shows ~160 characters).
   */
  excerpt?: string | null;
  /**
   * Required to publish. 16:9, at least 1200×675, with alt text. Set the focal point so crops look right.
   */
  cover?: (number | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Optional, up to 10. Used as article keywords (article:tag, JSON-LD).
   */
  tags?: string[] | null;
  /**
   * Up to 3. Empty: the site picks the latest posts of the same category.
   */
  relatedPosts?: (number | News)[] | null;
  /**
   * Only when the story is based on another outlet.
   */
  source?: {
    name?: string | null;
    url?: string | null;
  };
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Authors set "Awaiting review" when done. Editors approve or return "Needs changes". Becomes "Approved" on publish.
   */
  reviewStatus?: ('draft' | 'pending' | 'changes' | 'approved') | null;
  /**
   * Internal, never shown on the site.
   */
  reviewNote?: string | null;
  category: number | NewsCategory;
  /**
   * Empty: filled on first publish (scheduled too). Set by hand only to back-date. To schedule: arrow next to "Publish".
   */
  publishedAt?: string | null;
  author?: (number | null) | User;
  coAuthors?: (number | User)[] | null;
  /**
   * Pinned at the top of the News page.
   */
  featured?: boolean | null;
  /**
   * Marks the article as breaking news.
   */
  breaking?: boolean | null;
  /**
   * Computed on save.
   */
  readingTime?: number | null;
  /**
   * Set on save.
   */
  lastEditedBy?: (number | null) | User;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * Drag & drop or paste several images at once. JPG, PNG, WebP, AVIF, GIF up to 15 MB each; images are converted to WebP and capped at 2560 px. Alt text is prefilled from the file name - please refine it.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Short description for screen readers and Google. Left empty, it is filled from the file name.
   */
  alt?: string | null;
  /**
   * On when the alt was filled from the file name; cleared once you edit it.
   */
  altAuto?: boolean | null;
  /**
   * Shown under the image in articles (can be overridden per insert).
   */
  caption?: string | null;
  credit?: string | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    news?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
      | {
          relationTo?: 'videos';
          value: number | Video;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: ('media' | 'videos')[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Short clips and trailers for articles. MP4, WebM, MOV up to 300 MB; prefer MP4 (H.264) under 50 MB. Long videos: upload to YouTube and paste the link.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos".
 */
export interface Video {
  id: number;
  /**
   * Used for search and as the accessible title. Left empty, it is taken from the file name.
   */
  title?: string | null;
  /**
   * Shown before playback. Use the same aspect ratio as the video (usually 16:9).
   */
  poster?: (number | null) | Media;
  caption?: string | null;
  credit?: string | null;
  duration?: number | null;
  /**
   * Read from the MP4/MOV file on upload.
   */
  durationLabel?: string | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Groups shown as filters on the News page. Only admins add / delete (the slug is part of the URL); editors may rename.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-categories".
 */
export interface NewsCategory {
  id: number;
  name: string;
  /**
   * Leave empty to generate from the title. Shared by VI and EN.
   */
  slug?: string | null;
  description?: string | null;
  /**
   * Lower numbers come first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * CMS accounts. Only admins create accounts and change roles; there is no public sign-up.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  avatar?: (number | null) | Media;
  bio?: string | null;
  /**
   * Author: writes own articles and submits them. Editor: reviews, publishes, schedules any article and handles contact requests. Admin: everything incl. accounts and categories.
   */
  roles: ('admin' | 'editor' | 'author')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Requests sent from the Contact page. Submitted content is read-only; update the Status and the internal Note. Use the quick filters below or "Filters".
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-requests".
 */
export interface ContactRequest {
  id: number;
  name: string;
  email: string;
  type: 'biz' | 'support' | 'press' | 'other';
  subject: string;
  message: string;
  status: 'new' | 'processing' | 'done';
  /**
   * Visible to CMS users only.
   */
  note?: string | null;
  locale?: ('vi' | 'en') | null;
  /**
   * Salted SHA-256, used for rate limiting. The raw IP is never stored.
   */
  ipHash?: string | null;
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'news-categories';
        value: number | NewsCategory;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'videos';
        value: number | Video;
      } | null)
    | ({
        relationTo: 'contact-requests';
        value: number | ContactRequest;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  searchText?: T;
  excerpt?: T;
  cover?: T;
  content?: T;
  tags?: T;
  relatedPosts?: T;
  source?:
    | T
    | {
        name?: T;
        url?: T;
      };
  generateSlug?: T;
  slug?: T;
  reviewStatus?: T;
  reviewNote?: T;
  category?: T;
  publishedAt?: T;
  author?: T;
  coAuthors?: T;
  featured?: T;
  breaking?: T;
  readingTime?: T;
  lastEditedBy?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-categories_select".
 */
export interface NewsCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  altAuto?: T;
  caption?: T;
  credit?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        news?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos_select".
 */
export interface VideosSelect<T extends boolean = true> {
  title?: T;
  poster?: T;
  caption?: T;
  credit?: T;
  duration?: T;
  durationLabel?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-requests_select".
 */
export interface ContactRequestsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  type?: T;
  subject?: T;
  message?: T;
  status?: T;
  note?: T;
  locale?: T;
  ipHash?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  avatar?: T;
  bio?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'news';
      value: number | News;
    } | null;
    global?: string | null;
    user?: {
      relationTo: 'users';
      value: number | User;
    } | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock".
 */
export interface GalleryBlock {
  /**
   * Pick or drop several images at once (2-40). Drag to reorder.
   */
  images: (number | Media)[];
  layout?: ('grid' | 'slider') | null;
  columns?: ('2' | '3' | '4') | null;
  ratio?: ('auto' | '16:9' | '4:3' | '1:1') | null;
  showCaptions?: boolean | null;
  caption?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'gallery';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoEmbedBlock".
 */
export interface VideoEmbedBlock {
  source?: ('url' | 'upload') | null;
  /**
   * YouTube (incl. Shorts), Vimeo, Facebook video/reel, TikTok and .mp4/.webm files. The link is cleaned up on save.
   */
  url?: string | null;
  /**
   * Pick from the video library or drop an .mp4, .webm, .mov file (max 300 MB). Prefer 1080p.
   */
  file?: (number | null) | Video;
  /**
   * Optional. Shown before playback. Empty: YouTube uses its thumbnail, uploads use the poster from the video library.
   */
  poster?: (number | null) | Media;
  /**
   * Auto: Shorts, TikTok, Reels vertical; others 16:9.
   */
  aspectRatio?: ('auto' | '16:9' | '9:16' | '4:3' | '1:1') | null;
  autoplay?: boolean | null;
  title?: string | null;
  caption?: string | null;
  credit?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'videoEmbed';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SocialEmbedBlock".
 */
export interface SocialEmbedBlock {
  /**
   * Paste the link of a single public post on Facebook, X (Twitter), TikTok or Instagram.
   */
  url: string;
  caption?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'socialEmbed';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "QuoteBlock".
 */
export interface QuoteBlock {
  /**
   * No quotation marks needed.
   */
  text: string;
  author?: string | null;
  role?: string | null;
  /**
   * Optional.
   */
  sourceUrl?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'quote';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CalloutBlock".
 */
export interface CalloutBlock {
  variant?: ('note' | 'important' | 'warning') | null;
  title?: string | null;
  /**
   * Keep it short, 1-5 lines.
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'callout';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RelatedNewsBlock".
 */
export interface RelatedNewsBlock {
  title?: string | null;
  /**
   * Pick 1-3 published articles.
   */
  posts: (number | News)[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'relatedNews';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBlock".
 */
export interface CtaBlock {
  label: string;
  url: string;
  /**
   * Optional. Shown above the button.
   */
  note?: string | null;
  variant?: ('primary' | 'secondary') | null;
  newTab?: boolean | null;
  nofollow?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('plaintext' | 'bash' | 'javascript' | 'typescript' | 'json' | 'html' | 'css' | 'sql' | 'python') | null;
  code?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}