import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // CMS boundary of the public site (docs/CONNECT-CMS.md): site code talks to a
  // CMS only through src/site/lib/content (news) and src/site/lib/contact/sinks
  // (contact). Only the Payload adapter files below may import Payload.
  {
    files: ["src/site/**/*.{ts,tsx}", "src/app/(site)/**/*.{ts,tsx}", "src/app/sitemap.ts", "src/app/robots.ts"],
    ignores: [
      "src/site/lib/content/payload/**",
      "src/site/lib/contact/sinks/payload.ts",
      "src/site/components/news/body/LexicalBody.tsx",
      "src/site/components/news/rich-blocks/converters.tsx",
      // CMS health probe (checks Payload itself).
      "src/app/(site)/api/health/**",
    ],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              // Payload's live-preview bridge (a tiny client component) is the only allowed @/cms import.
              regex: "^(payload(/.*)?|@payload-config|@payloadcms/.*|@/cms/(?!live-preview/).*)$",
              message:
                "Public site code must not depend on the CMS. Use @site/lib/news (content sources in src/site/lib/content) or src/shared/* helpers.",
            },
          ],
        },
      ],
    },
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `payload migrate:create` / `generate:types` / `generate:importmap`.
    "src/cms/migrations/**",
    ".next-*/**",
  ]),
]);

export default eslintConfig;
